"""
ZOD dataset path utilities.

Preferred layout, generated by the current ZOD downloader:

    {zod_root}/
        sequences/
            000000/
                camera_front_blur/
                radar_front/
                calibration.json
                vehicle_data.hdf5

The legacy split-folder layout is supported as a fallback.
"""

from pathlib import Path


IMAGES_BLUR_RANGES = [
    (0, 490, "images_blur_000000_000490"),
    (491, 981, "images_blur_000491_000981"),
    (982, 1472, "images_blur_000982_001472"),
]


def normalize_sequence_id(seq: str | int) -> str:
    """Normalize a sequence ID to six digits, for example 490 -> 000490."""
    try:
        seq_int = int(seq)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"Invalid ZOD sequence ID: {seq!r}") from exc

    if not 0 <= seq_int <= 1472:
        raise ValueError(
            f"ZOD sequence ID out of range: {seq_int}. "
            "Expected a value from 000000 to 001472."
        )

    return f"{seq_int:06d}"


def get_sequence_dir(zod_root: Path, seq: str) -> Path:
    """
    Return the directory containing all data for one sequence.

    Current downloader layout:
        {zod_root}/sequences/{seq}

    A second candidate allows callers to pass {dataset}/sequences directly,
    although passing the actual dataset root is recommended.
    """
    zod_root = Path(zod_root).expanduser().resolve()
    seq = normalize_sequence_id(seq)

    candidates = [
        zod_root / "sequences" / seq,
        zod_root / seq,
    ]

    for candidate in candidates:
        if candidate.is_dir():
            return candidate

    attempted = "\n".join(f"  - {path}" for path in candidates)
    raise FileNotFoundError(
        f"ZOD sequence directory not found for sequence {seq}.\n"
        f"Tried:\n{attempted}\n"
        "Pass the dataset root, not an individual sequence directory."
    )


def _legacy_images_blur_dir(zod_root: Path, seq: str) -> Path:
    """Return the expected image path in the old split Dropbox layout."""
    seq = normalize_sequence_id(seq)
    seq_int = int(seq)

    for lo, hi, folder in IMAGES_BLUR_RANGES:
        if lo <= seq_int <= hi:
            return (
                Path(zod_root)
                / folder
                / "sequences"
                / seq
                / "camera_front_blur"
            )

    raise ValueError(f"Sequence outside supported ZOD range: {seq}")


def get_images_blur_dir(zod_root: Path, seq: str) -> Path:
    """Return camera_front_blur directory for a sequence."""
    zod_root = Path(zod_root).expanduser().resolve()
    seq = normalize_sequence_id(seq)

    # Current layout produced by `zod download`.
    modern_candidates = [
        zod_root / "sequences" / seq / "camera_front_blur",
        zod_root / seq / "camera_front_blur",
    ]

    for candidate in modern_candidates:
        if candidate.is_dir():
            return candidate

    # Backward compatibility with the old Dropbox layout.
    legacy_path = _legacy_images_blur_dir(zod_root, seq)
    if legacy_path.is_dir():
        return legacy_path

    attempted = modern_candidates + [legacy_path]
    attempted_text = "\n".join(f"  - {path}" for path in attempted)

    raise FileNotFoundError(
        f"camera_front_blur directory not found for sequence {seq}.\n"
        f"Tried:\n{attempted_text}"
    )


def get_radar_front_dir(zod_root: Path, seq: str) -> Path:
    """Return the radar_front directory for a sequence."""
    zod_root = Path(zod_root).expanduser().resolve()
    seq = normalize_sequence_id(seq)

    candidates = [
        # Current downloader layout.
        zod_root / "sequences" / seq / "radar_front",
        zod_root / seq / "radar_front",

        # Legacy Dropbox layout.
        zod_root / "radar_front" / "sequences" / seq / "radar_front",
    ]

    for candidate in candidates:
        if candidate.is_dir():
            return candidate

    attempted = "\n".join(f"  - {path}" for path in candidates)
    raise FileNotFoundError(
        f"radar_front directory not found for sequence {seq}.\n"
        f"Tried:\n{attempted}"
    )


def get_vehicle_data_path(zod_root: Path, seq: str) -> Path:
    """Return vehicle_data.hdf5 for a sequence."""
    zod_root = Path(zod_root).expanduser().resolve()
    seq = normalize_sequence_id(seq)

    candidates = [
        # Current downloader layout.
        zod_root / "sequences" / seq / "vehicle_data.hdf5",
        zod_root / seq / "vehicle_data.hdf5",

        # Legacy Dropbox layout.
        (
            zod_root
            / "vehicle_data"
            / "sequences"
            / seq
            / "vehicle_data.hdf5"
        ),
    ]

    for candidate in candidates:
        if candidate.is_file():
            return candidate

    attempted = "\n".join(f"  - {path}" for path in candidates)
    raise FileNotFoundError(
        f"vehicle_data.hdf5 not found for sequence {seq}.\n"
        f"Tried:\n{attempted}"
    )


def get_calibration_path(zod_root: Path, seq: str) -> Path:
    """Return calibration.json for a sequence."""
    zod_root = Path(zod_root).expanduser().resolve()
    seq = normalize_sequence_id(seq)

    candidates = [
        # Current downloader layout.
        zod_root / "sequences" / seq / "calibration.json",
        zod_root / seq / "calibration.json",

        # Legacy Dropbox layout.
        zod_root / "infos" / "sequences" / seq / "calibration.json",
    ]

    for candidate in candidates:
        if candidate.is_file():
            return candidate

    attempted = "\n".join(f"  - {path}" for path in candidates)
    raise FileNotFoundError(
        f"calibration.json not found for sequence {seq}.\n"
        f"Tried:\n{attempted}"
    )


def iter_all_sequences():
    """Yield sequence IDs 000000 through 001472."""
    for i in range(1473):
        yield f"{i:06d}"


def sequence_output_dir(zod_root: Path, seq: str) -> Path:
    """Return {zod_root}/output/{seq}."""
    seq = normalize_sequence_id(seq)
    return Path(zod_root).expanduser().resolve() / "output" / seq


def default_autospeed_checkpoint(zod_root: Path) -> Path:
    """Return {zod_root}/models/autospeed.pt."""
    return (
        Path(zod_root).expanduser().resolve()
        / "models"
        / "autospeed.pt"
    )